runtime: nodejs22

instance_class: F2

env_variables:
  DB_USERNAME: 'PLACEHOLDER_DB_USERNAME'
  DB_PASSWORD: 'PLACEHOLDER_DB_PASSWORD'
  DB_NAME: 'PLACEHOLDER_DB_NAME'
  DB_HOST: 'PLACEHOLDER_DB_HOST'
  BOT_TOKEN: 'PLACEHOLDER_BOT_TOKEN'
  INSTANCE_CONNECTION_NAME: 'PLACEHOLDER_INSTANCE_CONNECTION_NAME'
  JWT_SECRET_KEY: 'PLACEHOLDER_JWT_SECRET_KEY'
  TON_API_KEY: 'PLACEHOLDER_TON_API_KEY'
  TON_PUBLIC_KEY_HEX: 'PLACEHOLDER_TON_PUBLIC_KEY_HEX'
  TON_PRIVATE_KEY_HEX: 'PLACEHOLDER_TON_PRIVATE_KEY_HEX'
handlers:
  - url: /static
    static_dir: frontend/dist
  - url: /.*
    script: auto
  - url: /auth
    script: auto

beta_settings:
  cloud_sql_instances: PLACEHOLDER_INSTANCE_CONNECTION_NAME

entrypoint: npm run start:backend

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

network:
  forwarded_ports:
    - 8080
  instance_tag: my-tag
