runtime: nodejs22

instance_class: F2

env_variables:
  DB_USERNAME: 'PLACEHOLDER_DB_USERNAME'
  DB_PASSWORD: 'PLACEHOLDER_DB_PASSWORD'
  DB_NAME: 'PLACEHOLDER_DB_NAME'
  DB_HOST: 'PLACEHOLDER_DB_HOST'
  BOT_TOKEN: 'PLACEHOLDER_BOT_TOKEN'
  INSTANCE_CONNECTION_NAME: 'PLACEHOLDER_INSTANCE_CONNECTION_NAME'

handlers:
  - url: /static
    static_dir: frontend/dist
  - url: /.*
    script: auto

beta_settings:
  cloud_sql_instances: PLACEHOLDER_INSTANCE_CONNECTION_NAME=tcp:5432

entrypoint: |
  echo $(whoami) \
  rm -f /cloudsql/PLACEHOLDER_INSTANCE_CONNECTION_NAME/.s.PGSQL.5432 && \
  mkdir -p /cloudsql && chmod 777 /cloudsql &&  \
  ./cloud_sql_proxy -dir=/cloudsql -instances=PLACEHOLDER_INSTANCE_CONNECTION_NAME & \
  npm run start:backend

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

network:
  forwarded_ports:
    - 8080
  instance_tag: my-tag
