runtime: nodejs22

instance_class: F2

env_variables:
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_NAME: ${DB_NAME}
  DB_HOST: ${DB_HOST}

handlers:
  - url: /static
    static_dir: frontend/dist
  - url: /.*
    script: auto

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

network:
  forwarded_ports:
    - 8080
  instance_tag: my-tag
