name: Backend CI

on:
  workflow_call:
    secrets:
      DB_USERNAME:
        required: true
      DB_PASSWORD:
        required: true
      DB_NAME:
        required: true
      DB_HOST:
        required: true
      GCP_SERVICE_ACCOUNT_KEY:
        required: true
jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: './backend/package-lock.json'

    - name: Install dependencies
      run: npm install --prefix backend

    - name: Authenticate to Google Cloud
      run: |
        echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > ${HOME}/gcp-key.json
        gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
        gcloud --quiet config set project ${{ secrets.GCP_PROJECT }}

    - name: Install Cloud SQL Proxy
      run: |
        wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
        chmod +x cloud_sql_proxy

    - name: Start Cloud SQL Proxy
      run: |
        ./cloud_sql_proxy -instances=${{ secrets.DB_HOST }}=tcp:5432 &
      env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_HOST: 127.0.0.1

    - name: Wait for Cloud SQL Proxy to be ready
      run: |
        until nc -z -v -w30 127.0.0.1 5432
        do
          echo "Waiting for Cloud SQL Proxy to be ready..."
          sleep 5
        done

    - name: Run database migrations
      run: |
        cd backend
        npm run migrate
      env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_HOST: 127.0.0.1
        DB_PORT: 5432

    - name: Run tests
      run: |
        cd backend
        npm test
      env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
