name: Backend CI

on:
  workflow_call:
    secrets:
      DB_USERNAME:
        required: true
      DB_PASSWORD:
        required: true
      DB_NAME:
        required: true
      DB_HOST:
          required: true

jobs:
  backend:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_HOST: ${{ secrets.DB_HOST }}
        options: >-
          --health-cmd="pg_isready -U $DB_USERNAME"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 5432:5432

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: './backend/package-lock.json'

    - name: Install dependencies
      run: npm install --prefix backend

    - name: Wait for PostgreSQL
      run: |
        until pg_isready -h ${{ secrets.DB_HOST }} -p 5432 -U ${{ secrets.DB_USERNAME }}; do
          echo waiting for postgres
          sleep 2
        done

    - name: Run migrations
      env:
        DB_USER: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_HOST: ${{ secrets.DB_HOST }}
      run: npm run migrate --prefix backend

    - name: Compile TypeScript
      run: npm run build --prefix backend

    - name: Run tests
      env:
        DATABASE_URL: postgres://${{ secrets.DB_USERNAME }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:5432/${{ secrets.DB_NAME }}
      run: npm test --prefix backend
