name: Main CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  backend:
    uses: ./.github/workflows/ci-backend.yml
    secrets:
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_HOST: ${{ secrets.DB_HOST}}

  frontend:
    uses: ./.github/workflows/ci-frontend.yml
