name: Deploy to Yandex Cloud

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        push: true
        tags: cr.yandex/crp864q0vdo1e470updf/my-app:latest
        build-args: |
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_HOST=${{ secrets.DB_HOST }}

    - name: Set up Yandex CLI
      run: |
        curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
        echo "${{ secrets.YC_OAUTH_TOKEN }}" | yc init --token
        yc config set cloud-id ${ secrets.YC_CLOUD_ID }
        yc config set folder-id ${ secrets.YC_FOLDER_ID }
        yc config set compute-default-zone ru-central1-a

    - name: Set up kubectl
      run: |
        yc managed-kubernetes cluster get-credentials ton-btl-cluster --external --force
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

    - name: Deploy to Kubernetes
      env:
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_URL: ${{ secrets.DB_URL }}
      run: |
        # Create secret.yaml
        echo "apiVersion: v1
        kind: Secret
        metadata:
          name: my-app-secret
        type: Opaque
        data:
          database-url: $(echo -n $DB_URL | base64)
          db-username: $(echo -n $DB_USERNAME | base64)
          db-password: $(echo -n $DB_PASSWORD | base64)
          db-name: $(echo -n $DB_NAME | base64)
          db-host: $(echo -n $DB_HOST | base64)" > secret.yaml

        kubectl apply -f secret.yaml
        kubectl apply -f backend/deployment.yaml
        kubectl apply -f backend/service.yaml
