name: Deploy to Yandex Cloud

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Install Yandex CLI
      run: |
        curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -a

    - name: Check environment variables
      run: |
        echo "Checking environment variables:"
        echo "PATH=$PATH"
        ls -la /home/runner/yandex-cloud/
        ls -la /home/runner/yandex-cloud/bin/
        cat /home/runner/yandex-cloud/path.bash.inc
        source '/home/runner/yandex-cloud/path.bash.inc'
        echo "PATH=$PATH"
        echo '/home/runner/yandex-cloud/bin' >> $GITHUB_PATH

    - name: Set up Yandex CLI
      run: |
        echo "PATH=$PATH"
        echo $GITHUB_PATH
        ls -la $HOME/yandex-cloud/bin
        yc init --token "${{ secrets.YC_OAUTH_TOKEN }}"
        yc config set cloud-id ${{ secrets.YC_CLOUD_ID }}
        yc config set folder-id ${{ secrets.YC_FOLDER_ID }}
        yc config set compute-default-zone ru-central1-a
  
    - name: Log in to Yandex Container Registry
      run: |
        yc container registry configure-docker
  
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        push: true
        tags: cr.yandex/crp864q0vdo1e470updf/my-app:latest

    - name: Set up kubectl
      run: |
        yc managed-kubernetes cluster get-credentials ton-btl-cluster --external --force
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

    - name: Run database migrations
      env:
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_HOST: ${{ secrets.DB_HOST }}
      run: |
        npm run migrate

    - name: Apply Kubernetes Secrets and Deployment
      run: |
        kubectl apply -f backend/deployment.yaml
        kubectl apply -f backend/service.yaml
