name: Deploy to Google App Engine

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies for backend
      run: |
        cd backend
        npm install

    - name: Build backend
      run: |
        cd backend
        npm run build

    - name: Deploy to Google App Engine
      env:
        GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      run: |
        echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > ${HOME}/gcp-key.json
        gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
        gcloud --quiet config set project ${{ secrets.GCP_PROJECT }}
        gcloud app deploy app.yaml --quiet
